name: Matrix Upload

on:
  repository_dispatch:
    types:
      - "matrix-upload"

jobs:
  upload-all:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(github.event.client_payload) }}
    steps:
      - name: Run a multi-line script
        run: |
          echo ${{ matrix }}
