on:
  pull_request:
    types:
      - closed

jobs:
  echo_if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    name: PR ${{ github.event.number }} was merged
    steps:
    - run: |
      echo "I merged"
      echo "${{ github.event.number }}"
